### ISSUE TITLE
Return type const char* is a string

### ISSUE THREAD

**Issue by zembrowski** [dstogov/php-ffi#42]
Why is the result of `const char *` a `string` and `char *` a „byte-array“? 

A simple example:
```php
$ffi = FFI::cdef(
  "const char *strerror(int errnum);",
  "libc.so.6"
);
var_dump($ffi->strerror(1));
```

returns
```php
string(23) "Operation not permitted"
```

Removing `const` from the definition returns:
```php
object(FFI\CData:char*)#1074 (1) {
  [0]=>
  string(1) "O"
}
```

**Background**

A function of an external C library returns binary data which includes NULL-bytes. When `const` is in the definition the resulting string is not complete = shortened to the first NULL-byte = corrupt file.

**My workaround**

Remove `const` from the definition and
```php
$byteArray = $ffi->strerror(1);
$string = FFI::string($byteArray);
```
returns the correct complete string.

(In the real-life scenario the `$size` for `FFI::string($byteArray, $size)` is known and returned back from a different function of the C library.)

**Comment by dstogov** [comment]
@zembrowski  you are right about inconsistency.

However, it's more common for C APIs to return pointer to constant zero terminated strings (e.g. strerror), and read binary file content into buffer (e.g. read). You found workaround yourself. It's also possible to use "const unsigned char".

I don't see a perfect solution, because both options make sense.
At this moment, I can't change this behavior, anyway.

**Comment by zembrowski** [comment]
Thank you for your answer Dmitry.
